import type {
  AppStoreState,
  AvailabilityOverride,
  AvailabilityTemplate,
  Employer,
  PlanningWindow,
  Shift,
  UserProfile,
} from "./models"
import { buildTimeEntryFromClockSession } from "./timeEntries"

const employerDirectory: Employer[] = [
  {
    id: "bistro-noir",
    code: "BIST01",
    name: "Bistro Noir",
    type: "Restaurant",
    city: "Brussels",
    teamSize: 12,
    rating: 4.8,
  },
  {
    id: "grand-cafe",
    code: "GRAN02",
    name: "Grand Cafe",
    type: "Cafe",
    city: "Brussels",
    teamSize: 8,
    rating: 4.6,
  },
  {
    id: "lux-hotel",
    code: "LUXH03",
    name: "The Lux Hotel",
    type: "Hotel",
    city: "Brussels",
    teamSize: 45,
    rating: 4.9,
  },
  {
    id: "terra-italiana",
    code: "TERR14",
    name: "Terrazza Italiana",
    type: "Restaurant",
    city: "Ghent",
    teamSize: 14,
    rating: 4.6,
  },
  {
    id: "harbor-bakery",
    code: "HARB25",
    name: "Harbor Bakery",
    type: "Bakery",
    city: "Antwerp",
    teamSize: 9,
    rating: 4.7,
  },
  {
    id: "canal-bar",
    code: "CANA36",
    name: "Canal Bar",
    type: "Bar",
    city: "Brussels",
    teamSize: 11,
    rating: 4.5,
  },
]

const profile: UserProfile = {
  id: "sofia-fischer",
  firstName: "Sofia",
  lastName: "Fischer",
  email: "demo.employee@vesta.local",
  role: "Waiter",
  preferredName: "Sofia",
  phone: "",
  dateOfBirth: "",
  nationality: "Belgian",
  homeCity: "Brussels",
  address: {
    street: "",
    postalCode: "",
    city: "Brussels",
    country: "Belgium",
  },
  emergencyContact: {
    name: "",
    relationship: "",
    phone: "",
  },
  onboardingComplete: true,
  bio: "Front-of-house employee balancing hospitality, availability planning, and shift swaps.",
  language: "English (UK)",
  motionPreference: "system",
  themePreference: "system",
  security: {
    faceIdEnabled: false,
    biometricType: "Face ID",
    passwordLastChangedAt: "Apr 12, 2026",
  },
  privacy: {
    analyticsEnabled: true,
    crashReportsEnabled: true,
    employerDataSharingEnabled: true,
  },
  bankAccount: {
    iban: "",
    bic: "",
    bankName: "",
    accountHolder: "",
  },
  legal: {
    nationalRegisterNumber: "",
    taxId: "",
    socialSecurityNumber: "",
    workPermitStatus: "EU/EEA citizen",
    payrollStatus: "Ready for payroll",
  },
  notificationPreferences: {
    shiftReminders: true,
    scheduleChanges: true,
    documentRequests: true,
    payslips: true,
    employerAnnouncements: false,
  },
}

const shifts: Shift[] = [
  {
    id: "shift-1",
    date: "2026-05-17",
    dayLabel: "Today",
    startTime: "17:00",
    endTime: "23:00",
    role: "Waiter",
    venueName: "Bistro Noir",
    venueAddress: "Rue de la Loi 123, Brussels",
    status: "confirmed",
    note: "Arrive 15 minutes early for team briefing.",
    coworkers: ["Emma D.", "Lucas M.", "Yasmine K."],
  },
  {
    id: "shift-2",
    date: "2026-05-18",
    dayLabel: "Mon",
    startTime: "12:00",
    endTime: "18:00",
    role: "Waiter",
    venueName: "Bistro Noir",
    venueAddress: "Rue de la Loi 123, Brussels",
    status: "confirmed",
    coworkers: ["Emma D.", "Noah P."],
  },
  {
    id: "shift-3",
    date: "2026-05-20",
    dayLabel: "Wed",
    startTime: "18:00",
    endTime: "23:30",
    role: "Waiter",
    venueName: "Bistro Noir",
    venueAddress: "Rue de la Loi 123, Brussels",
    status: "changed",
    note: "Kitchen closes later due to event service.",
    coworkers: ["Emma D.", "Lucas M.", "Yasmine K."],
    changeSummary: "End time moved from 23:00 to 23:30 for the event service.",
    requiresResponse: true,
    responseStatus: "pending",
  },
  {
    id: "shift-4",
    date: "2026-05-22",
    dayLabel: "Fri",
    startTime: "17:00",
    endTime: "00:00",
    role: "Bartender",
    venueName: "Bistro Noir",
    venueAddress: "Rue de la Loi 123, Brussels",
    status: "pending",
    coworkers: ["Mila R.", "Jonas T."],
    changeSummary: "Manager asked you to confirm this extra Friday bar shift.",
    requiresResponse: true,
    responseStatus: "pending",
  },
  {
    id: "shift-5",
    date: "2026-05-24",
    dayLabel: "Sun",
    startTime: "11:00",
    endTime: "17:00",
    role: "Waiter",
    venueName: "Bistro Noir",
    venueAddress: "Rue de la Loi 123, Brussels",
    status: "confirmed",
    coworkers: ["Emma D.", "Nina B."],
  },
  {
    id: "shift-6",
    date: "2026-05-27",
    dayLabel: "Wed",
    startTime: "17:00",
    endTime: "23:00",
    role: "Waiter",
    venueName: "Bistro Noir",
    venueAddress: "Rue de la Loi 123, Brussels",
    status: "confirmed",
    coworkers: ["Lara C.", "Noah P."],
  },
]

const availabilityTemplate: AvailabilityTemplate = {
  monday: { status: "available", startTime: "12:00", endTime: "22:00" },
  tuesday: { status: "preferred", startTime: "17:00", endTime: "23:00" },
  wednesday: { status: "available", startTime: "17:00", endTime: "23:30" },
  thursday: { status: "unavailable", startTime: "09:00", endTime: "17:00" },
  friday: { status: "preferred", startTime: "17:00", endTime: "00:00" },
  saturday: { status: "preferred", startTime: "12:00", endTime: "23:00" },
  sunday: { status: "available", startTime: "11:00", endTime: "18:00" },
}

const availabilityOverrides: Record<string, AvailabilityOverride> = {
  "2026-05-18": { date: "2026-05-18", status: "available", startTime: "12:00", endTime: "23:00" },
  "2026-05-19": { date: "2026-05-19", status: "preferred", startTime: "17:00", endTime: "23:00" },
  "2026-05-20": { date: "2026-05-20", status: "available", startTime: "17:00", endTime: "23:30" },
  "2026-05-21": {
    date: "2026-05-21",
    status: "unavailable",
    startTime: "09:00",
    endTime: "17:00",
    note: "Exam evening",
  },
  "2026-05-22": { date: "2026-05-22", status: "preferred", startTime: "17:00", endTime: "00:00" },
  "2026-05-23": { date: "2026-05-23", status: "preferred", startTime: "12:00", endTime: "23:00" },
}

const planningWindows: PlanningWindow[] = [
  {
    id: "planning-window-1",
    label: "Next week",
    startDate: "2026-05-18",
    endDate: "2026-05-24",
    deadline: "2026-05-18T18:00:00.000Z",
    status: "open",
  },
  {
    id: "planning-window-2",
    label: "May 25 - May 31",
    startDate: "2026-05-25",
    endDate: "2026-05-31",
    deadline: "2026-05-24T18:00:00.000Z",
    submittedAt: "2026-05-15T10:30:00.000Z",
    status: "submitted",
  },
]

export function buildNewTimeEntry(
  clockSession: AppStoreState["clockSession"],
  clockOutAt: string,
  clockOutLocation = clockSession.events[clockSession.events.length - 1]?.location,
) {
  return buildTimeEntryFromClockSession({
    clockOutAt,
    clockOutLocation,
    clockSession,
  })
}

export function createInitialState(): AppStoreState {
  return {
    authStatus: "signedOut",
    profile,
    employers: employerDirectory,
    employerDirectory,
    shifts,
    availabilityOverrides,
    availabilityTemplate,
    planningWindows,
    requests: [
      {
        id: "request-1",
        category: "time_off",
        type: "Time off",
        status: "pending",
        submittedAt: "2026-05-15T09:12:00.000Z",
        target: {
          kind: "dates",
          label: "May 26 - May 27",
          startDate: "2026-05-26",
          endDate: "2026-05-27",
        },
        reason: "Personal",
        statusDetail: "Waiting for manager review",
        nextStep: "Manager approval expected before Thursday",
      },
      {
        id: "request-2",
        category: "shift_change",
        type: "Shift swap",
        status: "approved",
        submittedAt: "2026-05-10T14:45:00.000Z",
        target: {
          kind: "shift",
          label: "May 12 evening shift",
          shiftId: "shift-1",
        },
        reason: "Swap evening shift with Lara",
        statusDetail: "Approved by Lara and manager",
        nextStep: "No further action needed",
      },
    ],
    documents: [
      {
        id: "document-1",
        title: "ID card verification",
        subtitle: "Required for payroll activation",
        category: "Identity",
        status: "action_required",
        ctaLabel: "Upload now",
      },
      {
        id: "document-2",
        title: "April payslip",
        subtitle: "Available for download",
        category: "Payroll",
        status: "available",
        ctaLabel: "View payslip",
      },
      {
        id: "document-3",
        title: "Employment contract",
        subtitle: "Signed and archived",
        category: "Contracts",
        status: "verified",
        ctaLabel: "View contract",
      },
    ],
    notifications: [
      {
        id: "notification-1",
        kind: "schedule",
        title: "Shift updated",
        body: "Friday May 22 now runs until midnight.",
        relativeTime: "1h ago",
        unread: true,
        action: { type: "navigate", route: "/(app)/shift/shift-4" },
      },
      {
        id: "notification-2",
        kind: "documents",
        title: "Document requested",
        body: "Upload your ID card to keep payroll on track.",
        relativeTime: "4h ago",
        unread: true,
        action: {
          type: "uploadDocument",
          documentId: "document-1",
          title: "ID card verification",
        },
      },
      {
        id: "notification-3",
        kind: "availability",
        title: "Availability deadline",
        body: "Set your availability for next week before Sunday evening.",
        relativeTime: "2d ago",
        unread: false,
        action: { type: "editAvailabilityOverride", date: "2026-05-18" },
      },
    ],
    timeEntries: [],
    clockSession: {
      state: "idle",
      accumulatedBreakSeconds: 0,
      scheduledStart: "17:00",
      scheduledEnd: "23:00",
      role: "Waiter",
      venueName: "Bistro Noir",
      venueAddress: "Rue de la Loi 123, Brussels",
      events: [],
    },
    earnings: {
      monthLabel: "May 2026",
      targetAmount: 2400,
      earnedAmount: 0,
      shiftsWorked: 0,
      hoursWorked: 0,
      averageHourlyRate: 12.02,
    },
    highlights: [
      {
        id: "highlight-1",
        title: "Earned this month",
        value: "EUR 0.00",
        subtitle: "0% of your monthly target",
      },
      {
        id: "highlight-2",
        title: "Today's shift",
        value: "17:00 - 23:00",
        subtitle: "Clock in at Bistro Noir to start tracking hours",
      },
      {
        id: "highlight-3",
        title: "Response score",
        value: "98%",
        subtitle: "You confirm schedule changes quickly",
      },
    ],
    tasks: [
      {
        id: "task-1",
        title: "Upload your ID card",
        subtitle: "Required before the next payroll run",
        urgency: "high",
        actionLabel: "Upload",
        action: {
          type: "uploadDocument",
          documentId: "document-1",
          title: "ID card verification",
        },
      },
      {
        id: "task-2",
        title: "Review updated Wednesday shift",
        subtitle: "Your end time changed due to event service",
        urgency: "medium",
        actionLabel: "Review",
        action: { type: "respondToShift", shiftId: "shift-3" },
      },
      {
        id: "task-3",
        title: "Set next week's availability",
        subtitle: "Help the team finalize rota planning",
        urgency: "low",
        actionLabel: "Set",
        action: { type: "editAvailabilityOverride", date: "2026-05-18" },
      },
    ],
    signedContractIds: ["contract-1"],
  }
}
