import { format } from "date-fns"

import type {
  AppStoreState,
  AvailabilityDay,
  Employer,
  TimeEntry,
  Shift,
  UserProfile,
} from "./models"

const employerDirectory: Employer[] = [
  {
    id: "bistro-noir",
    code: "BIST01",
    name: "Bistro Noir",
    type: "Restaurant",
    city: "Brussels",
    teamSize: 12,
    rating: 4.8,
    active: true,
  },
  {
    id: "grand-cafe",
    code: "GRAN02",
    name: "Grand Cafe",
    type: "Cafe",
    city: "Brussels",
    teamSize: 8,
    rating: 4.6,
  },
  {
    id: "lux-hotel",
    code: "LUXH03",
    name: "The Lux Hotel",
    type: "Hotel",
    city: "Brussels",
    teamSize: 45,
    rating: 4.9,
  },
  {
    id: "terra-italiana",
    code: "TERR14",
    name: "Terrazza Italiana",
    type: "Restaurant",
    city: "Ghent",
    teamSize: 14,
    rating: 4.6,
  },
  {
    id: "harbor-bakery",
    code: "HARB25",
    name: "Harbor Bakery",
    type: "Bakery",
    city: "Antwerp",
    teamSize: 9,
    rating: 4.7,
  },
  {
    id: "canal-bar",
    code: "CANA36",
    name: "Canal Bar",
    type: "Bar",
    city: "Brussels",
    teamSize: 11,
    rating: 4.5,
  },
]

const profile: UserProfile = {
  id: "sofia-fischer",
  firstName: "Sofia",
  lastName: "Fischer",
  email: "demo.employee@vesta.local",
  role: "Waiter",
  preferredName: "Sofia",
  phone: "",
  dateOfBirth: "",
  nationality: "Belgian",
  homeCity: "Brussels",
  address: {
    street: "",
    postalCode: "",
    city: "Brussels",
    country: "Belgium",
  },
  emergencyContact: {
    name: "",
    relationship: "",
    phone: "",
  },
  onboardingComplete: true,
  bio: "Front-of-house employee balancing hospitality, availability planning, and shift swaps.",
  language: "English (UK)",
  themePreference: "system",
  security: {
    faceIdEnabled: false,
    biometricType: "Face ID",
    passwordLastChangedAt: "Apr 12, 2026",
  },
  privacy: {
    analyticsEnabled: true,
    crashReportsEnabled: true,
    employerDataSharingEnabled: true,
  },
  bankAccount: {
    iban: "",
    bic: "",
    bankName: "",
    accountHolder: "",
  },
  legal: {
    nationalRegisterNumber: "",
    taxId: "",
    socialSecurityNumber: "",
    workPermitStatus: "EU/EEA citizen",
    payrollStatus: "Ready for payroll",
  },
  notificationPreferences: {
    shiftReminders: true,
    scheduleChanges: true,
    documentRequests: true,
    payslips: true,
    employerAnnouncements: false,
  },
}

const shifts: Shift[] = [
  {
    id: "shift-1",
    date: "2026-05-17",
    dayLabel: "Today",
    startTime: "17:00",
    endTime: "23:00",
    role: "Waiter",
    venueName: "Bistro Noir",
    venueAddress: "Rue de la Loi 123, Brussels",
    status: "confirmed",
    note: "Arrive 15 minutes early for team briefing.",
  },
  {
    id: "shift-2",
    date: "2026-05-18",
    dayLabel: "Mon",
    startTime: "12:00",
    endTime: "18:00",
    role: "Waiter",
    venueName: "Bistro Noir",
    venueAddress: "Rue de la Loi 123, Brussels",
    status: "confirmed",
  },
  {
    id: "shift-3",
    date: "2026-05-20",
    dayLabel: "Wed",
    startTime: "18:00",
    endTime: "23:30",
    role: "Waiter",
    venueName: "Bistro Noir",
    venueAddress: "Rue de la Loi 123, Brussels",
    status: "changed",
    note: "Kitchen closes later due to event service.",
  },
  {
    id: "shift-4",
    date: "2026-05-22",
    dayLabel: "Fri",
    startTime: "17:00",
    endTime: "00:00",
    role: "Bartender",
    venueName: "Bistro Noir",
    venueAddress: "Rue de la Loi 123, Brussels",
    status: "pending",
  },
  {
    id: "shift-5",
    date: "2026-05-24",
    dayLabel: "Sun",
    startTime: "11:00",
    endTime: "17:00",
    role: "Waiter",
    venueName: "Bistro Noir",
    venueAddress: "Rue de la Loi 123, Brussels",
    status: "confirmed",
  },
  {
    id: "shift-6",
    date: "2026-05-27",
    dayLabel: "Wed",
    startTime: "17:00",
    endTime: "23:00",
    role: "Waiter",
    venueName: "Bistro Noir",
    venueAddress: "Rue de la Loi 123, Brussels",
    status: "confirmed",
  },
]

const availability: Record<string, AvailabilityDay> = {
  "2026-05-18": { date: "2026-05-18", status: "available", startTime: "12:00", endTime: "23:00" },
  "2026-05-19": { date: "2026-05-19", status: "preferred", startTime: "17:00", endTime: "23:00" },
  "2026-05-20": { date: "2026-05-20", status: "available", startTime: "17:00", endTime: "23:30" },
  "2026-05-21": { date: "2026-05-21", status: "unavailable", startTime: "09:00", endTime: "17:00" },
  "2026-05-22": { date: "2026-05-22", status: "preferred", startTime: "17:00", endTime: "00:00" },
  "2026-05-23": { date: "2026-05-23", status: "preferred", startTime: "12:00", endTime: "23:00" },
}

const timeEntries: TimeEntry[] = [
  {
    id: "time-1",
    date: "2026-05-16",
    shiftLabel: "Evening",
    clockIn: "17:03",
    clockOut: "23:04",
    breakMinutes: 30,
    totalHoursLabel: "5h 31m",
    earningsLabel: "EUR 66.24",
    status: "approved",
  },
  {
    id: "time-2",
    date: "2026-05-14",
    shiftLabel: "Lunch",
    clockIn: "12:03",
    clockOut: "18:02",
    breakMinutes: 30,
    totalHoursLabel: "5h 29m",
    earningsLabel: "EUR 65.84",
    status: "approved",
  },
  {
    id: "time-3",
    date: "2026-05-12",
    shiftLabel: "Evening",
    clockIn: "17:05",
    clockOut: "23:15",
    breakMinutes: 30,
    totalHoursLabel: "5h 40m",
    earningsLabel: "EUR 68.00",
    status: "approved",
  },
]

export function buildNewTimeEntry(payableSeconds: number, breakSeconds: number): TimeEntry {
  const totalHours = Math.floor(payableSeconds / 3600)
  const totalMinutes = Math.floor((payableSeconds % 3600) / 60)
  const earningsAmount = (payableSeconds / 3600) * 12.02
  return {
    id: `time-${Date.now()}`,
    date: format(new Date(), "yyyy-MM-dd"),
    shiftLabel: "Clocked shift",
    clockIn: format(new Date(Date.now() - payableSeconds * 1000 - breakSeconds * 1000), "HH:mm"),
    clockOut: format(new Date(), "HH:mm"),
    breakMinutes: Math.floor(breakSeconds / 60),
    totalHoursLabel: `${totalHours}h ${totalMinutes}m`,
    earningsLabel: `EUR ${earningsAmount.toFixed(2)}`,
    status: "review",
  }
}

export function createInitialState(): AppStoreState {
  return {
    authStatus: "signedOut",
    profile,
    activeEmployerId: "bistro-noir",
    employers: employerDirectory.map((employer) => ({
      ...employer,
      active: employer.id === "bistro-noir",
    })),
    employerDirectory,
    shifts,
    availability,
    requests: [
      {
        id: "request-1",
        type: "Time off",
        status: "pending",
        dateRange: "May 26 - May 27",
        reason: "Personal",
      },
      {
        id: "request-2",
        type: "Shift swap",
        status: "approved",
        dateRange: "May 12",
        reason: "Swap evening shift with Lara",
      },
    ],
    documents: [
      {
        id: "document-1",
        title: "ID card verification",
        subtitle: "Required for payroll activation",
        category: "Identity",
        status: "action_required",
        ctaLabel: "Upload now",
      },
      {
        id: "document-2",
        title: "April payslip",
        subtitle: "Available for download",
        category: "Payroll",
        status: "available",
        ctaLabel: "View payslip",
      },
      {
        id: "document-3",
        title: "Employment contract",
        subtitle: "Signed and archived",
        category: "Contracts",
        status: "verified",
        ctaLabel: "View contract",
      },
    ],
    notifications: [
      {
        id: "notification-1",
        kind: "schedule",
        title: "Shift updated",
        body: "Friday May 22 now runs until midnight.",
        relativeTime: "1h ago",
        unread: true,
        deepLink: "/shift/shift-4",
      },
      {
        id: "notification-2",
        kind: "documents",
        title: "Document requested",
        body: "Upload your ID card to keep payroll on track.",
        relativeTime: "4h ago",
        unread: true,
        deepLink: "/(app)/(tabs)/documents",
      },
      {
        id: "notification-3",
        kind: "availability",
        title: "Availability deadline",
        body: "Set your availability for next week before Sunday evening.",
        relativeTime: "2d ago",
        unread: false,
        deepLink: "/(app)/(tabs)/schedule",
      },
    ],
    timeEntries,
    clockSession: {
      state: "idle",
      accumulatedBreakSeconds: 0,
      scheduledStart: "17:00",
      scheduledEnd: "23:00",
      role: "Waiter",
      venueName: "Bistro Noir",
      venueAddress: "Rue de la Loi 123, Brussels",
    },
    earnings: {
      monthLabel: "May 2026",
      targetAmount: 2400,
      earnedAmount: 847.2,
      shiftsWorked: 7,
      hoursWorked: 41.5,
      averageHourlyRate: 12.02,
    },
    highlights: [
      {
        id: "highlight-1",
        title: "Earned this month",
        value: "EUR 847.20",
        subtitle: "35% of your monthly target",
      },
      {
        id: "highlight-2",
        title: "Hours this week",
        value: "23.5h",
        subtitle: "2 more shifts scheduled",
      },
      {
        id: "highlight-3",
        title: "Response score",
        value: "98%",
        subtitle: "You confirm schedule changes quickly",
      },
    ],
    tasks: [
      {
        id: "task-1",
        title: "Upload your ID card",
        subtitle: "Required before the next payroll run",
        urgency: "high",
        actionLabel: "Upload",
        href: "/(app)/(tabs)/documents",
      },
      {
        id: "task-2",
        title: "Review updated Friday shift",
        subtitle: "Kitchen event added 1 extra hour",
        urgency: "medium",
        actionLabel: "Review",
        href: "/shift/shift-4",
      },
      {
        id: "task-3",
        title: "Set next week's availability",
        subtitle: "Help the team finalize rota planning",
        urgency: "low",
        actionLabel: "Set",
        href: "/(app)/(tabs)/schedule",
      },
    ],
    signedContractIds: ["contract-1"],
  }
}
